### ISSUE TITLE
include domain name in resulting local path

### ISSUE THREAD

**Issue by deanmalmgren** [gabegaster/django-offlinecdn#6]
`https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js` should be stored at `cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js` within the `OFFLINECDN_STATIC_ROOT` and hosted at `{{OFFLINECDN_STATIC_URL}}cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.js`. currently the cdnjs.cloudflare.com part of the url is not included, which could resulting problems if some other CDN has the same path but has a different version of d3 stored there (for some odd reason)

**Comment by gabegaster** [comment]
Good idea, this is addressed by 373a27e84f74bca82e9db8029a153d9d8c0ebb91
